# Generated by Django 4.2.1 on 2023-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypermarket', '0002_alter_buyer_discount_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
